# Generated by Django 5.0.6 on 2024-11-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='selected_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
