# Generated by Django 5.0.6 on 2024-11-01 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobapplications_selected_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_status', models.BooleanField(blank=True, default=False, null=True)),
                ('invit_description', models.TextField(blank=True, null=True)),
                ('job_requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobrequirements')),
                ('jobprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobproviderregister')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobseekerregister')),
            ],
        ),
    ]
