# Generated by Django 5.0.6 on 2024-11-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_invitation_exam_link_invitation_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
