# Generated by Django 5.0.6 on 2024-11-01 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_delete_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_limit', models.IntegerField(help_text='Time limit in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobrequirements')),
                ('jobprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobproviderregister')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('max_marks', models.IntegerField(help_text='Maximum marks for this question')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='job.exam')),
            ],
        ),
    ]
