# Generated by Django 5.0.6 on 2024-11-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_exam_examquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
