# Generated by Django 5.0.6 on 2024-11-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_remove_examquestion_answer_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_log',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_status',
        ),
        migrations.AddField(
            model_name='answers',
            name='exam_log',
            field=models.TextField(blank=True, default='good', null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='exam_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
