# Generated by Django 5.0.6 on 2024-10-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobproviderprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequirements',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
