# Generated by Django 5.0.6 on 2024-11-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_invitation_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
