# Generated by Django 5.0.6 on 2024-11-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_exam_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_log',
            field=models.TextField(blank=True, default='good', null=True),
        ),
    ]
