# Generated by Django 5.0.6 on 2024-11-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_exam_exam_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='scored',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
