# Generated by Django 5.0.6 on 2024-11-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_examquestion_scored'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
