# Generated by Django 5.0.6 on 2024-11-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_examquestion_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='answer',
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('marks_scored', models.IntegerField(blank=True, default=0, null=True)),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.examquestion')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobseekerregister')),
            ],
        ),
    ]
